/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        error: {
          DEFAULT: "#ef4444",
          foreground: "#ffffff",
        },
        "error-container": "#fee2e2",
        "on-primary": "hsl(var(--primary-foreground))",
        // Design system color tokens from .design/DESIGN.md
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#424754",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "outline": "#727785",
        "outline-variant": "#c2c6d6",
        "surface-tint": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "primary-container": "#2170e4",
        "on-primary-container": "#fefcff",
        "inverse-primary": "#adc6ff",
        "secondary-token": "#6b38d4",
        "on-secondary": "#ffffff",
        "secondary-container": "#8455ef",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary": "#b10e6b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d23284",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffd9e4",
        "tertiary-fixed-dim": "#ffb0cd",
        "on-tertiary-fixed": "#3e0022",
        "on-tertiary-fixed-variant": "#8c0053",
        "error-token": "#ba1a1a",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        quicksand: ["Quicksand", "sans-serif"],
        nunito: ["Nunito Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px" }],
        "headline-md": ["20px", { lineHeight: "28px" }],
        "label-bold": ["14px", { lineHeight: "20px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "body-lg": ["18px", { lineHeight: "26px" }],
        "label-status": ["12px", { lineHeight: "16px" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        drift: {
          "from": { transform: "translate(-10%, -10%) scale(1)" },
          "to": { transform: "translate(10%, 10%) scale(1.1)" },
        },
        scanning: {
          "0%": { top: "-2px", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { top: "100%", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        drift: "drift 20s infinite alternate ease-in-out",
        scanning: "scanning 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
